name: fv
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pip:
    - torch>=2.2.0
    - datasets==2.14.3
    - jupyter==1.0.0
    - matplotlib==3.7.1
    - numpy==1.25.0
    - pandas==1.5.3
    - plotly==5.9.0
    - scikit-learn==1.3.0
    - seaborn==0.12.2
    - sentencepiece==0.1.99
    - tqdm==4.65.0
    - transformers==4.51.3
    - huggingface-hub==0.30.0
    - accelerate==0.26.0
    - bitsandbytes==0.45.3
    - git+https://github.com/davidbau/baukit@main#egg=baukit
